# .github/workflows/test.yml
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Validate API Spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - run: inso --version
      - name: CD
        run: cd /home/runner/work/DineazyInsomniaTests/DineazyInsomniaTests
      - name: list files
        run: ls
      - name: run tests
        run: inso run test --src /home/runner/work/DineazyInsomniaTests/DineazyInsomniaTests/InsomniaCollection.json --env dev --ci
