# # .github/workflows/test.yml

# name: Test

# jobs:
#   Linux:
#     name: Validate API spec
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout branch
#         uses: actions/checkout@v1
#       - uses: kong/setup-inso@v1
#         with:
#           inso-version: 2.4.0
#       # - name: Lint
#       #   run: inso lint spec "Designer Demo" --ci
#       - name: Run test suites
#         run: inso run test "DineazyTestDocument" --env dev --ci
#       # - name: Generate declarative config
#       #   run: inso generate config "Designer Demo" --type declarative --ci

# This is a basic workflow to help you get started with Actions

name: Inso CLI Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0

      # Runs a single command using the runners shell
      - name: Run test suites
        run: inso run test "DineazyTestDocument" --env dev --ci
