# .github/workflows/test.yml
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Validate API Spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - run: inso --version
      - name: Lint
        run: inso lint spec "DineazyTestDocument" --ci
      - name: Run test suites
        run: inso run test "DineazyTestDocument" --env dev --ci
      - name: Generate declarative config
        run: inso generate config "DineazyTestDocument" --type declarative --ci
